### ISSUE TITLE
How do you test your controllers?

### ISSUE THREAD

**Issue by gvolpe** [merle-/silhouette-rest-seed#3]
I'm trying to test my controllers using the Silhouette Testkit following the [documentation](http://docs.silhouette.mohiva.com/en/latest/how-it-works/testing.html) with a JWTAuthenticator instead of a CookieAuthenticator but I always get a 401 http status. This is the exception:
```
[[31merror[0m] c.m.p.s.a.e.AuthenticationException - [Silhouette][jwt-authenticator] Error on parsing JWT token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0MjU2OTY3OTksInN1YiI6Ijc4MGViNmNlYmE2OTg4Mjc4ZjVjM2Q1MDQ3YzU0NTM2YjE5Njg1NzJmNWIyNWRmOTJjZGI1M2VlN2M0YjJlYzFiYWEwZGJmY2JkMjIwNzQ4NzU4YjcyYzliZGYyZDY0MzUzZGJhOWQ2MmI2NGZmZjY3Y2Q1MDBjYTFkNGFhMWYwIiwiaXNzIjoicGxheS1zaWxob3VldHRlIiwianRpIjoiMWY5OWEzMjYxOTM4OTFmM2I0NjU0MDQwYTEyYzExZjJiY2M1NDkyM2FkMTk0NWY5ZGNkOTBkNGE4ZGIxOTlkMzk3ZWRmNWZmNmNjYTgxNzVhYjc5ZWIyY2ZjYzE0ZTgzZjUwZWY2ZjNjZWMwMDQzMDUxYzQ2ZDI4MzcwYzZjYjllYmUwNGE2M2JjMmY1ZWJmY2RiNTE3MWIxOWJhMWRiNmJjMzE0YjMzNDNkMjkzNGU0MjM0MWFiNTVjM2QxZTZiNDBmYjAxNzJiMjNlOWYxNDdlZjMwNjlhZWY0NDM3NTE5ODc1NzI2N2M5NzdhMmNlZGQ1ZWY1YzVlZTdkNGU3OCIsImlhdCI6MTQyNTY1MzU5OX0.vuK9hUfB4J8oA59f3IvW-y8xKr_C-oNOZA1g40GL0ak
java.lang.IllegalArgumentException: Fraudulent JWT token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0MjU2OTY3OTksInN1YiI6Ijc4MGViNmNlYmE2OTg4Mjc4ZjVjM2Q1MDQ3YzU0NTM2YjE5Njg1NzJmNWIyNWRmOTJjZGI1M2VlN2M0YjJlYzFiYWEwZGJmY2JkMjIwNzQ4NzU4YjcyYzliZGYyZDY0MzUzZGJhOWQ2MmI2NGZmZjY3Y2Q1MDBjYTFkNGFhMWYwIiwiaXNzIjoicGxheS1zaWxob3VldHRlIiwianRpIjoiMWY5OWEzMjYxOTM4OTFmM2I0NjU0MDQwYTEyYzExZjJiY2M1NDkyM2FkMTk0NWY5ZGNkOTBkNGE4ZGIxOTlkMzk3ZWRmNWZmNmNjYTgxNzVhYjc5ZWIyY2ZjYzE0ZTgzZjUwZWY2ZjNjZWMwMDQzMDUxYzQ2ZDI4MzcwYzZjYjllYmUwNGE2M2JjMmY1ZWJmY2RiNTE3MWIxOWJhMWRiNmJjMzE0YjMzNDNkMjkzNGU0MjM0MWFiNTVjM2QxZTZiNDBmYjAxNzJiMjNlOWYxNDdlZjMwNjlhZWY0NDM3NTE5ODc1NzI2N2M5NzdhMmNlZGQ1ZWY1YzVlZTdkNGU3OCIsImlhdCI6MTQyNTY1MzU5OX0.vuK9hUfB4J8oA59f3IvW-y8xKr_C-oNOZA1g40GL0ak
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService$$anonfun$unserialize$2.apply(JWTAuthenticator.scala:301) ~[play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService$$anonfun$unserialize$2.apply(JWTAuthenticator.scala:297) ~[play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.5.jar:na]
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService.unserialize(JWTAuthenticator.scala:297) ~[play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService$$anonfun$retrieve$3.apply(JWTAuthenticator.scala:144) [play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
[[31merror[0m] c.m.p.s.a.e.AuthenticationException - [Silhouette][jwt-authenticator] Error on parsing JWT token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0MjU2OTY3OTksInN1YiI6Ijc4MGViNmNlYmE2OTg4Mjc4ZjVjM2Q1MDQ3YzU0NTM2YjE5Njg1NzJmNWIyNWRmOTJjZGI1M2VlN2M0YjJlYzFiYWEwZGJmY2JkMjIwNzQ4NzU4YjcyYzliZGYyZDY0MzUzZGJhOWQ2MmI2NGZmZjY3Y2Q1MDBjYTFkNGFhMWYwIiwiaXNzIjoicGxheS1zaWxob3VldHRlIiwianRpIjoiMWY5OWEzMjYxOTM4OTFmM2I0NjU0MDQwYTEyYzExZjJiY2M1NDkyM2FkMTk0NWY5ZGNkOTBkNGE4ZGIxOTlkMzk3ZWRmNWZmNmNjYTgxNzVhYjc5ZWIyY2ZjYzE0ZTgzZjUwZWY2ZjNjZWMwMDQzMDUxYzQ2ZDI4MzcwYzZjYjllYmUwNGE2M2JjMmY1ZWJmY2RiNTE3MWIxOWJhMWRiNmJjMzE0YjMzNDNkMjkzNGU0MjM0MWFiNTVjM2QxZTZiNDBmYjAxNzJiMjNlOWYxNDdlZjMwNjlhZWY0NDM3NTE5ODc1NzI2N2M5NzdhMmNlZGQ1ZWY1YzVlZTdkNGU3OCIsImlhdCI6MTQyNTY1MzU5OX0.vuK9hUfB4J8oA59f3IvW-y8xKr_C-oNOZA1g40GL0ak
java.lang.IllegalArgumentException: Fraudulent JWT token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0MjU2OTY3OTksInN1YiI6Ijc4MGViNmNlYmE2OTg4Mjc4ZjVjM2Q1MDQ3YzU0NTM2YjE5Njg1NzJmNWIyNWRmOTJjZGI1M2VlN2M0YjJlYzFiYWEwZGJmY2JkMjIwNzQ4NzU4YjcyYzliZGYyZDY0MzUzZGJhOWQ2MmI2NGZmZjY3Y2Q1MDBjYTFkNGFhMWYwIiwiaXNzIjoicGxheS1zaWxob3VldHRlIiwianRpIjoiMWY5OWEzMjYxOTM4OTFmM2I0NjU0MDQwYTEyYzExZjJiY2M1NDkyM2FkMTk0NWY5ZGNkOTBkNGE4ZGIxOTlkMzk3ZWRmNWZmNmNjYTgxNzVhYjc5ZWIyY2ZjYzE0ZTgzZjUwZWY2ZjNjZWMwMDQzMDUxYzQ2ZDI4MzcwYzZjYjllYmUwNGE2M2JjMmY1ZWJmY2RiNTE3MWIxOWJhMWRiNmJjMzE0YjMzNDNkMjkzNGU0MjM0MWFiNTVjM2QxZTZiNDBmYjAxNzJiMjNlOWYxNDdlZjMwNjlhZWY0NDM3NTE5ODc1NzI2N2M5NzdhMmNlZGQ1ZWY1YzVlZTdkNGU3OCIsImlhdCI6MTQyNTY1MzU5OX0.vuK9hUfB4J8oA59f3IvW-y8xKr_C-oNOZA1g40GL0ak
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService$$anonfun$unserialize$2.apply(JWTAuthenticator.scala:301) ~[play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService$$anonfun$unserialize$2.apply(JWTAuthenticator.scala:297) ~[play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.5.jar:na]
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService.unserialize(JWTAuthenticator.scala:297) ~[play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]
	at com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticatorService$$anonfun$retrieve$3.apply(JWTAuthenticator.scala:144) [play-silhouette_2.11-2.0-RC1.jar:2.0-RC1]UserController should

'401' is not equal to '201'
```

**Comment by akkie** [comment]
Hi,

I think you are referencing to this [code](https://github.com/gvolpe/social-graph-api/blob/master/test/controllers/UserControllerSpec.scala#L59). If so then make sure that the environment in your test case is the same as in your controller. Maybe you can pass the environment as argument from your test to the controller.

If this doesn't solve your issue, then please provide an isolated test case.

Cheers,
Christian

**Comment by merle-** [comment]
Hi! Here an example that works. I will provide some test within next week

```scala
package controllers

import org.specs2.mutable._
import play.api.test._
import com.mohiva.play.silhouette.test._
import com.mohiva.play.silhouette.api.LoginInfo
import com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator
import models.users._
import models.authorizations._
import scala.reflect.runtime.universe

class RestApplicationControllerSpec extends PlaySpecification {

  val baseInfo = BaseInfo(
    firstName = Some("Ale"),
    lastName = Some("Random"),
    fullName = None,
    gender = Some("M"))
  val user = User(
    id = java.util.UUID.randomUUID.toString,
    loginInfo = LoginInfo("facebook", "apollonia.vanova@watchmen.com"),
    socials = None,
    email = None,
    username = None,
    avatarUrl = None,
    info = baseInfo,
    roles = Set(SimpleUser))

  "The `user` method" should {
    "return status 200 if authenticator and identity was found" in new WithApplication {
      val identity = user //User(LoginInfo("facebook", "apollonia.vanova@watchmen.com"))
      implicit val fakeEnv = FakeEnvironment[User, JWTAuthenticator](Seq(identity.loginInfo -> identity))
      val request = FakeRequest().withAuthenticator(identity.loginInfo)

      val controller = new controllers.RestApplicationController {
        override implicit lazy val env = fakeEnv
      }
      val result = controller.onlyGodOrUser(request)
      
      status(result) must equalTo(OK)
      contentAsString(result) mustEqual "{\"result\":\"Oh yess GOD\"}"
    }
  }

}
```

**Comment by gvolpe** [comment]
Thank you so much merle! It's working now --> https://github.com/gvolpe/social-graph-api
